### ISSUE TITLE
Can't install sodium in GNU/Linux

### ISSUE THREAD

**Issue by iembry-USGS** [jeroenooms/sodium#1]
Hi, I am using R 3.2.3 on GNU/Linux Trisquel 7.0/Ubuntu Trusty with libsodium13.

I am getting the following installation error:

    seal.c: In function ‘R_seal_open’:
    seal.c:19:21: error: ‘crypto_box_SEALBYTES’ undeclared (first use in this function)
    int mlen = clen - crypto_box_SEALBYTES;
                     ^
    seal.c:23:3: warning: implicit declaration of function ‘crypto_box_seal_open’ [-Wimplicit-function- 
    declaration]
    if(crypto_box_seal_open(RAW(res), RAW(cipher), clen, pk, RAW(key)))
    ^
    make: *** [seal.o] Error 1
    ERROR: compilation failed for package ‘sodium’
    * removing ‘/home/uoxyh/R/x86_64-pc-linux-gnu-library/library/sodium’

Do I need to first configure libsodium prior to installing sodium?

Thank you.

Irucka Embry

**Comment by jedisct1** [comment]
Maybe your libsodium version is too old.
`crypto_box_seal` was introduced in version 1.0.3.
But the R bindings should check that these macros are present in order to be compatible with old versions.

**Comment by jeroenooms** [comment]
Not sure where you got your libsodium (it does not come with ubuntu 14.04) but you can grab a suitable version from launchpad: https://launchpad.net/~chris-lea/+archive/ubuntu/libsodium

**Comment by jeroenooms** [comment]
I added a readme file to the repo to make this a bit more obvious :D

**Comment by iembry-USGS** [comment]
Thank you, I appreciate that.
