### ISSUE TITLE
Can't install sodium on shinyapps.io

### ISSUE THREAD

**Issue by jdarot** [jeroenooms/sodium#2]
Hi,

I am trying to deploy a shiny app that uses the sodium package.

The app works works fine locally, but when using the deployApp() function, the installation of sodium on shinyapps.io fails, and I get the log below.

I assume this is an issue with shinyapps.io, not sodium, but could you perhaps tell them how to make it work on their server?

Thanks,
Jeremy

Preparing to deploy application...DONE
Uploading bundle for application: 72254...DONE
Deploying bundle: 398669 for application: 72254 ...
Waiting for task: 170651245
  building: Processing bundle: 398669
  building: Parsing manifest
  building: Building image: 391991
  building: Fetching packages
  building: Building package: sodium
################################ Begin Task Log ################################ 
[2016-03-18T22:43:33.892330609+0000] Installing R package: xtable (1.8-0)
* installing to library ‘/usr/local/lib/R/site-library’
* installing *binary* package ‘xtable’ ...
* DONE (xtable)
[2016-03-18T22:43:34.184885917+0000] Installing R package: labeling (0.3)
* installing to library ‘/usr/local/lib/R/site-library’
* installing *binary* package ‘labeling’ ...
* DONE (labeling)
[2016-03-18T22:43:34.440812487+0000] Building R package: sodium (0.2)
/mnt/packages/build /mnt
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘sodium’ ...
** package ‘sodium’ successfully unpacked and MD5 sums checked
Package libsodium was not found in the pkg-config search path.
Perhaps you should add the directory containing `libsodium.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libsodium' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lsodium
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libsodium was not found. Try installing:
 * deb: libsodium-dev (Debian, Ubuntu, etc)
 * rpm: libsodium-devel (Fedora, EPEL)
 * csw: libsodium_dev (Solaris)
 * brew: libsodium (OSX)
If libsodium is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libsodium.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘sodium’
* removing ‘/usr/local/lib/R/site-library/sodium’
################################# End Task Log ################################# 
Error: Unhandled Exception: Child Task 170651260 failed: Error building image: Error building sodium (0.2). Build exited with non-zero status: 1

**Comment by jeroenooms** [comment]
You need to ask the rstudio folks to install `libsodium-dev` on the shinyapps.io server.

**Comment by jdarot** [comment]
Thanks Jeroen, will do.

Cheers,
Jeremy

**Comment by CBarraford** [comment]
@jdarot you can add support for sodium, via opening a pull request on https://github.com/rstudio/shinyapps-package-dependencies

**Comment by jdarot** [comment]
Thanks, I just did at https://github.com/rstudio/shinyapps-package-dependencies/issues/37.
